### ISSUE TITLE
Memory Error 

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/rosie#24] opened 2017-01-26 12:54 UTC
Okay so I have an notebook running Ubuntu 15.10 with an Intel® Core™ i7 CPU M 640 and 4 GB RAM. and yet since 2015 was added to `AnosAnteriores.xml` it is impossible for Rosie to run in a computer such as mine without giving a `MemoryError`.
[Here](https://gist.github.com/jtemporal/b322e939eadbac8b472f3bcb1d64c2fd) is the traceback of the error.

When talking with @cuducos about it, he brought up [Dask](http://dask.pydata.org/) which should take longer than pandas but would help people with such configurations as mine run Rosie.

**Comment by jtemporal** [comment] 2017-01-30 14:26
also ran using docker and it gives out the [MemoryError](https://gist.github.com/jtemporal/fbfbb10172672e710d30caf9d54b86e9)

**Comment by vmesel** [comment] 2017-02-11 12:42
Have you tried to use low_memory=True on pandas?

**Comment by jtemporal** [comment] 2017-02-11 12:58
@vmesel yes, and yet my computer just can handle it =/

**Comment by fariaslcfs** [comment] 2017-02-11 19:38
@jtemporal @cuducos 
How about dividing reimbursements as per year basis and generating the irregularities.xz file also per year? The worst memory comsumption o@ccurs after merging reimbursements with companies during the generation of the irregularities.xz file. The highest memory, I/O and process use(and in my case the PC halts) starts by the run_classifiers() method.  Then we need to feed de DB with all the irregularities and such.
Just a thought.
Ths

**Comment by vmesel** [comment] 2017-02-13 22:01
@jtemporal how about creating a pickle of the dataframe and then using it to load into RAM? I think it would solve your problem!

**Comment by fariaslcfs** [comment] 2017-02-14 08:43
@vmesel Isn't this the memory issue?

**Comment by vmesel** [comment] 2017-02-14 12:22
@fariaslcfs I suggested you to open an issue about low memory users using these data, because it should be accessible by any one on any computer. Probably they can split the files and publish a reduced size csv for each year for users like you and @jtemporal

**Comment by vanessasoutoc** [comment] 2017-02-14 13:02
I have the same error and I already told you low_memory=True

How to soluction for this bug??

[Error](https://gist.github.com/vanessasoutoc/771812dd9a370f55e1ecebe8458b3c5e)

**Comment by fariaslcfs** [comment] 2017-02-14 13:49
@vmesel Sorry buddy, actually I hadn't understood your sugestion. I am just trying to adapt some pieces of code in order to have Rosie finally running completely  in my system (i5 4th generation with 6GB dedicated). I have noticed when running Rosie that we have not only a memory problem, but also too much I/O and even an excessive processor use. I'll certainly post anything that I think may help Rosie work smoothly anywhere,
Tks

**Comment by cuducos** [comment] 2017-02-14 13:51
> Dask provides multi-core execution on larger-than-memory datasets using blocked algorithms and task scheduling

That's what we're debating here. So far my suggestion was widely ignored: use [Dask](https://pypi.python.org/pypi/dask/) as it, according to its documentation:

> provides multi-core execution on larger-than-memory datasets using blocked algorithms and task scheduling.

This seems more concrete than @vmesel's hacks of splitting the datasets or using pickle — let's Dask deal with this low level transaction for us, yay!

Unfortunately it looks like no one was able to send a PR or to code and share some of these ideas, but thats part of open source projects live cycle ; )

**Comment by fariaslcfs** [comment] 2017-02-14 15:31
@cuducos As soon as I finish what you called hacks (I call "gato" kkk),  I'll try Dask. At first, I need to really understand completely that awesome project you and the team you're a member of have designed. When I get deep into the code by 'hacking' or even debbuging I learn much faster. 
Tks

**Comment by jtemporal** [comment] 2017-02-24 13:52
@vmesel I think that the problem is what @fariaslcfs decribed in his comment
>I have noticed when running Rosie that we have not only a memory problem, but also too much I/O and even an excessive processor use

and I believe that's what is causing the memory issue (at least in my machine)... Also there is a number of reasons we should not to pickle the data, a few of them are described in this [awesome blog post](http://www.benfrederickson.com/dont-pickle-your-data/) by @benfred.

@fariaslcfs if you would like, I love to help you on

>understand completely that awesome project

Making Rosie run on lower budget computers like mine is something that I'm particularly interested, ping me over telegram and we can discuss it and maybe schedule a hangouts =)

thank you guys for discussing this subject \o/ your insights are very helpful.

**Comment by jtemporal** [comment] 2017-02-24 14:28
@vanessasoutoc could you share your computer configuration?

**Comment by vanessasoutoc** [comment] 2017-02-24 14:32
@jtemporal Ubuntu 16.04 LTS, Intel® Core™ i5-6500 CPU @ 3.20GHz × 4, 7,7GB memory RAM, 1TB HD

**Comment by jtemporal** [comment] 2017-02-24 14:48
@vanessasoutoc thanks! right now AFAIK Rosie only runs on a 16GB RAM computer, because she does demand a huge amount of processing and memory to handle all the data she needs as input =/
We believe that's why you (and I) are getting that nasty memory error.
I hope that sooner better than later will be able to get her running on a 8GB RAM machine. But I don't know when that will happen =(

**Comment by luizcavalcanti** [comment] 2017-04-04 19:36
Interestingly enough, it runs on my i5/8GB/macOS machine. Is anyone else unable to reproduce this error?

**Comment by cuducos** [comment] 2017-05-02 13:02
> We monitored it with newrelic, and soon we will publish resulting report.

Yay! Looking forward to check that ; )

**Comment by cuducos** [comment] 2017-05-10 20:28
In an informal chat wth @rafonseca he suggested us to transform `string` categorial data using the `.astype('category')` method. In a test I just made it reduces the amont of memory used by `congressperson_name` in 75%:

```
In [1]: import pandas as pd

In [2]: df = pd.read_csv('data/2016-12-06-reimbursements.xz')
/usr/local/var/pyenv/versions/anaconda3-4.1.1/envs/serenata_de_amor/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2683: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]: df['congressperson_name'].nbytes
Out[3]: 12318568

In [4]: df['congressperson_name'].astype('category').nbytes
Out[4]: 3088802
```

**Comment by rafonseca** [comment] 2017-05-12 14:15
From the traceback posted by @jtemporal up there, I understand that all datasets are merged into a big pandas dataframe. Two things can be done about this
1- Put this big dataframe into a Dask dataframe. I think this will reduce memory usage and speed up in almost any machine. Dask splits the dataframe in the disk and manages parallel operations.
2- Do not compose a big dataframe. Instead, compose specific dataframes for each classifier. This can be achieved using 'usecols' at pd.read_csv. Ideally after a classifier has done its prediction, its specific dataframe should be discarded. Here, Dask comes again to the rescue. A Dask task graph can manage all that.
I have some more things to say about the classifiers internal memory use, but I will leave it for another moment.

**Comment by paulochf** [comment] 2017-05-24 18:28
Adding to @cuducos suggestion, these kind of optimizations can save a lot of space.

Another one is to reduce the `int` types. Sometimes, some int column has a restricted value domain, like a limited range (i.e. [1; 5]). Pandas will keep them on a `int64` column, but changing to `int8` will save up some space.

Another one is missing data. Integer columns with missing (`nan`) values make Pandas to save them in object/float columns. Mapping missing values to some valid value (i.e. -1) allow changing the column type to `int`, hence reducing its size.

Although, the main big disadvantage is that forces keeping an eye on data types. We never know when the data source change its schema, which is not so scalable.

Said that, if Dask can manage the memory it uses, fewer tweaks are needed on the dataframe columns.

**Comment by Irio** [comment] 2017-07-22 19:45
@jtemporal Is this `MemoryError` error still present?

**Comment by jtemporal** [comment] 2017-07-23 16:26
>@jtemporal Is this MemoryError error still present?

I'll run it again on my old computer this week to test and log here the results =)

**Comment by anderson-sousa** [comment] 2017-08-19 16:32
@jtemporal @Irio `MemoryError` still present running Docker. PC Specs: Ubuntu 17.04, Intel® Core™ i7-4790K CPU @ 4.4GHz, 16GB RAM.

**Comment by apast** [comment] 2017-08-19 21:15
Hello,

I am late replying for this.

Recently, we ran an experiment supporting extended memory usage.

At our last Florianopolis' Serenata meeting, our experiment consisted on:

. Create a 5$ Digital Ocean droplet (512 MB RAM, 20 GB SSD storage)
. Create a large swap file with 8GB
. Run Rosie fully without memory issues

Considering SSD storage throughput, it is reasonable to use unused storage
space as extended memory.

Result: It works well!

We evaluate performance using New Relic metrics. My mistake was not send it
to Serenata group or attach to this issue.

Maybe it is naive and well known procedure, but it works fine on
development or limited resourced environments. I consider a good approach
for production environments for non mission critical or real time
environments.

**Comment by cuducos** [comment] 2017-11-29 13:33
Closed by inactivity and considering that:

* It's expected that Rosie consumes a lot of memory
* Discussions here might be outdated as Rosie has evolved since August (date of the previous comment in the thread)
* Surely anyone is free to open a new issue with more detailed and specific issues related to memory usage ; )

**Closed by cuducos** 2017-11-29 13:33 UTC
Labels: enhancement
